server:
  port: 8000
spring:
  application:
    name: gateway-zuul-customer-route-locator
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com.example.gatewayzuul: debug
    org.springframework.cloud.netflix.zuul.filters: debug
