server:
  port: 8000
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    abc:
      path: /account/**
      serviceId: MICROSERVICE-USER-WITH-EUREKA

logging:
  level:
    com.example.gatewayzuul: debug
    org.springframework.cloud.netflix.zuul.filters: debug

