spring:
  application:
    name: microservice-school-rest-template-hystrix
server:
  port: 9010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.example.microserviceschool.controller: trace
    com.example.microserviceschool.service: trace
endpoints:
  health:
    sensitive: false

