spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vision1v1/spring-demo
          repos:
            dev:
              pattern:
                - '*/dev'
                - '*/staging'
              uri: https://github.com/vision1v1/spring-demo
              search-paths: spring-cloud-demo/config-repo/dev
            sit:
              pattern:
                - '*/sit'
              uri: https://github.com/vision1v1/spring-demo
              search-paths: spring-cloud-demo/config-repo/sit
            uat:
              pattern:
                - '*/uat'
              uri: https://github.com/vision1v1/spring-demo
              search-paths: spring-cloud-demo/config-repo/uat

           # 从github上clone到本地的存放位置，但是在使用用户密码方式访问配置服务器时，重新拉取配置会出现异常
#          basedir: c://config-repo-temp
#        health:
#          repositories:
#            microservice-user:
#              label: master
  security:
    user:
      password: test123
      name: test
server:
  port: 7777
